name: Build Zmeika APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            git cmake ninja-build \
            python3-venv python3-dev openjdk-17-jdk

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools virtualenv wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0 websockets

      - name: Create buildozer.spec
        run: |
          cat <<EOT > buildozer.spec
          [app]
          title = Zmeika Multiplayer
          package.name = zmeika
          package.domain = org.example
          source.dir = .
          source.include_exts = py,kv
          version = 1.0
          requirements = python3,kivy==2.3.0,websockets
          orientation = portrait
          fullscreen = 1
          android.archs = armeabi-v7a
          android.permissions = INTERNET
          android.minapi = 33
          android.api = 34
          android.ndk = 25b
          android.release_artifact = apk
          android.accept_sdk_license = True
          log_level = 2
          entrypoint = main.py

          [buildozer]
          warn_on_root = 1
          EOT

      - name: Setup Android NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d tmp
          mv tmp/cmdline-tools latest
          rm -rf tmp commandlinetools-linux-9477386_latest.zip

          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$HOME/.buildozer/android/platform/android-sdk/platform-tools:$HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Setup Python-for-Android
        run: |
          mkdir -p $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          git clone --depth 1 --branch develop https://github.com/kivy/python-for-android.git $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          cd $GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android
          pip install -e .

      - name: Build APK
        run: |
          export BUILD_DIR=$GITHUB_WORKSPACE
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b

          cd $BUILD_DIR
          buildozer -v android clean
          buildozer -v android release

          if ls bin/*.apk 1> /dev/null 2>&1; then
            cp bin/*.apk zmeika-unsigned.apk
          else
            echo "APK generation failed!"
            tail -n 100 .buildozer/android/platform/build-armeabi-v7a/build/build.log || echo "Log not found"
            exit 1
          fi

      - name: Generate debug keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Sign APK manually
        run: |
          apksigner sign --ks debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android --key-pass pass:android zmeika-unsigned.apk
          mv zmeika-unsigned.apk zmeika-app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: zmeika-apk
          path: zmeika-app.apk
          if-no-files-found: error
          retention-days: 5
